export { SchoolPage } from './data/school'
export { TeachersPages, ChangeUserPage } from './data/teachers'
export { ClassesPage } from './data/classes'
export { StudentsPage, ChangeStudentPage } from './data/students'
export { CalculationPage } from './meals/calculation'
